export const aboutSetting = {
  titleOne: "Welcome to CropOffs",
  titleTwo: "Be safe, be secure!!",
  titleThree: "For media enquiries please contact us at:",
  descriptionOne: `<p class="text-lg"> An upcycled jewellery brand started by a woman who has always loved fashion but wanted a make a difference. <br /> Our motto is to help women to dress in a more eco-friendly way, with less waste & more love, while still looking stylish.</p>`,
  descriptionTwo:
    "<p>To protect against the loss, misuse and alteration of the information under its control, the Company has in place appropriate physical, electronic and managerial procedures. For example, the Company servers are accessible only to authorized personnel and your information is shared with employees and authorized personnel on a need to know basis to complete the transaction and to provide the services requested by you. Although the Company endeavour to safeguard the confidentiality of your personally identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By using the website, you agree that the Company will have no liability for disclosure of your information due to errors in transmission and/or unauthorized acts of third parties.</p><p>Please note that the Company will not ask you to share any sensitive data or information via email or telephone. If you receive any such request by email or telephone, please do not respond/divulge any sensitive data or information and forward the information relating to the same to &nbsp;<a href='mailto:info@borobazar.com'>info@borobazar.com</a>&nbsp; for necessary action.</p>",
  descriptionThree:
    "<p>Built on a proprietary technology stack, the Grocers platform serves as a convergence of consumers looking for everyday essentials, partner stores who serve their needs efficiently, and manufacturers looking for a channel to reach a nation of consumers. While our technology caters to the burgeoning population of urban India, it is ready and poised to serve the next 100+ million Indians who are yet to start shopping online.</p><p>We believe the ecosystem we power can transform the lives of a billion Indians significantly over the coming decade. They will have access to everyday essentials like groceries at the best value, be able to discover products that improve their health and wellbeing, and spend more meaningful time with their families – with the assurance that their essential needs are being looked after by us. On the other side of this virtuous cycle are the millions of local businesses catering to a nation’s needs, helping create more opportunities for employment, growth, and above all, a better life.</p>",
  descriptionFour:
    "<p>BoroBazar is leading the charge in transforming India’s vast, unorganized grocery landscape through cutting-edge technology and innovation. We believe every Indian deserves the opportunity to continually improve their life – a process that often begins at home. As part of our mission of helping consumers make healthier, better choices when buying everyday products, we make a wide range of high-quality grocery and household products accessible, affordable, and available right at their doorsteps.</p>",
  descriptionFive:
    "<p>For all other inquiries, visit our &nbsp;<a href='https://redq.io/'>Contact Us</a>&nbsp; page.</p>",
};
